In [1]:
# Importing Libraries

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
#Creating helper functions

def get_title_from_index(index):
    return df[df.index == index]["title"].values[0]

def get_index_from_title(title):
    return df[df.title == title]["index"].values[0]

In [16]:
##################################################

##Step 1: Read CSV File

df=pd.read_csv("movie_dataset.csv")

df

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [18]:
# Viewing available features
print(df.columns)

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [23]:
##Step 2: Select Features

features=["keywords","cast","genres","director"]

features

# Filling up NaN values

for feature in features:
    df[feature]=df[feature].fillna(" ")

In [32]:
##Step 3: Create a column in DF which combines all selected features

def combine_features(row):
    return row["keywords"]+" "+row["cast"]+" "+row["genres"]+row["director"]


df["combined_features"] = df.apply(combine_features , axis=1)

print (df["combined_features"].head())

0    culture clash future space war space colony so...
1    ocean drug abuse exotic island east india trad...
2    spy based on novel secret agent sequel mi6 Dan...
3    dc comics crime fighter terrorist secret ident...
4    based on novel mars medallion space travel pri...
Name: combined_features, dtype: object

In [35]:
##Step 4: Create count matrix from this new combined column

cv = CountVectorizer()

count_matrix = cv.fit_transform(df["combined_features"])

print(count_matrix)

  (0, 3603)	1
  (0, 2744)	1
  (0, 6192)	1
  (0, 14211)	2
  (0, 16331)	1
  (0, 2881)	1
  (0, 14125)	1
  (0, 13359)	1
  (0, 16776)	1
  (0, 17031)	1
  (0, 13334)	1
  (0, 13962)	1
  (0, 16464)	1
  (0, 14390)	1
  (0, 8937)	1
  (0, 10243)	1
  (0, 12759)	1
  (0, 86)	1
  (0, 216)	1
  (0, 5486)	1
  (0, 13585)	1
  (0, 5763)	1
  (0, 2192)	1
  (1, 216)	1
  (1, 5486)	1
  :	:
  (4801, 11633)	1
  (4801, 7138)	1
  (4801, 397)	1
  (4801, 5006)	1
  (4801, 17007)	1
  (4801, 13209)	1
  (4801, 3326)	1
  (4801, 13871)	1
  (4801, 7612)	1
  (4802, 11230)	1
  (4802, 4722)	1
  (4802, 1920)	1
  (4802, 5117)	1
  (4802, 6484)	1
  (4802, 3260)	1
  (4802, 4731)	1
  (4802, 1215)	1
  (4802, 12728)	1
  (4802, 4804)	1
  (4802, 2187)	1
  (4802, 6699)	1
  (4802, 3581)	1
  (4802, 5635)	1
  (4802, 7194)	2
  (4802, 4163)	1

In [43]:
##Step 5: Compute the Cosine Similarity based on the count_matrix

cosine_sim = cosine_similarity(count_matrix) 
movie_user_likes = "Titanic"

In [47]:
## Step 6: Get index of this movie from its title
movie_index = get_index_from_title(movie_user_likes)

similar_movies =  list(enumerate(cosine_sim[movie_index]))

In [48]:
## Step 7: Getting a list of similar movies in descending order of similarity score


sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)

In [49]:
## Step 8: Print titles of first 50 movies

i=0
for movie in sorted_similar_movies:
        print (get_title_from_index(movie[0]))
        i=i+1
        if i>50:
            break

Titanic
Me You and Five Bucks
Revolutionary Road
The Day the Earth Stood Still
Almost Famous
Gangs of New York
The Beach
The Bridge of San Luis Rey
Cheri
Little Black Book
The Aviator
Heavenly Creatures
Django Unchained
The Wolf of Wall Street
The Departed
J. Edgar
The Great Gatsby
All the King's Men
The Life of David Gale
The Reader
Celebrity
Flushed Away
Blood Diamond
Eternal Sunshine of the Spotless Mind
Wonderland
The Holiday
Shutter Island
Ever After: A Cinderella Story
Sense and Sensibility
Little Children
Vanilla Sky
Primary Colors
Contagion
Catch Me If You Can
About Schmidt
When Harry Met Sally...
Valley of the Wolves: Iraq
Body of Lies
Laws of Attraction
Steve Jobs
Shortbus
Your Sister's Sister
Boynton Beach Club
In the Valley of Elah
What's Eating Gilbert Grape
Fido
The Host
Iris
Tammy
Flying By
August